# OSPanel: Laravel routing for localhost/Kitob/public
location /Kitob/public/ {
    try_files $uri $uri/ /Kitob/public/index.php?$query_string;
}

location ~ ^/Kitob/public/.*\.php$ {
    try_files      $fastcgi_script_name =404;
    fastcgi_pass   backend;
    include        '%sprogdir%/userdata/config/nginx_fastcgi_params.txt';
}
